org: faith
app: talk-to-me
service: backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x


plugins:
  - serverless-offline


functions:
  api:
    handler: handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
      - cors: true

custom:
  serverless-offline:
    httpPort: 5000